"""初始化数据库

Revision ID: 2f72a30694e3
Revises: 
Create Date: 2025-05-22 19:30:51.401742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f72a30694e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('name', sa.String(length=32), nullable=True, comment='角色名称'),
    sa.Column('remark', sa.String(length=100), nullable=True, comment='备注'),
    sa.Column('role_key', sa.String(length=32), nullable=True, comment='角色标识'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色'
    )
    with op.batch_alter_table('t_access_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=32), nullable=False, comment='用户名'))
        batch_op.alter_column('is_deleted',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_comment='逻辑删除:0=未删除,1=删除',
               existing_nullable=True)
        batch_op.create_table_comment(
        't_access_token',
        'Token',
        existing_comment=None,
        schema=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_access_token', schema=None) as batch_op:
        batch_op.drop_table_comment(
        't_access_token',
        existing_comment='Token',
        schema=None
    )
        batch_op.alter_column('is_deleted',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_comment='逻辑删除:0=未删除,1=删除',
               existing_nullable=True)
        batch_op.drop_column('user_name')

    op.drop_table('t_role')
    # ### end Alembic commands ###
